#%RAML 1.0
title: library-security-schema
baseUri: /libraryand securityschema.com:8081

mediaType: [application/json, application/xml]
uses:
  complexLib: library.raml

traits:
  errorResoponse: !include traits/errorTrait.raml

types:
  simpleDatatype: !include datatypes/accounts_payableDataType.raml

securitySchemes:
  custSecurityScheme: !include common/security-scheme.raml
  
securedBy:
    - custSecurityScheme  

/accounts-receivable:
  description: call name aaccounts receivable
  get:
    is: [errorResoponse]
    responses:
      200:
        body:
          application/json:
            example: !include examples/accounts_receivable.json
            type: complexLib.accountsRec[]

/accounts-payable:
  post:
    is: [errorResoponse]
    body:
      application/json:
        example: !include examples/accounts_payable.json
        type: simpleDatatype[]
    responses:
      201:
       body:
         application/json:
           example: { "message" : " sucess status"}